### ISSUE TITLE
No handler for type [geo_shape] declared on field [geometry]

### ISSUE THREAD

**Issue by red-fenix** [codelibs/opensearch-runner#3]
[Photon](https://github.com/komoot/photon) uses the opensearch runner for a local instance using testing and production. [Whilst creating a pull request](https://github.com/komoot/photon/pull/823), I ran into a problem.
When adding the geo_shape field in the [index mapping](https://github.com/komoot/photon/pull/823/commits/d544bb380ddb037cdb694f5d1ac38543f3d01ee1#diff-0b75c092ba0ca07c504654ac880a2fc5fa75af7cff773786a88997d18fd34040) and running, the OpenSearch runner gives the error:

`No handler for type [geo_shape] declared on field [geometry]`

The [geo_shape is  a valid field](https://opensearch.org/docs/latest/field-types/supported-field-types/geo-shape/), but unfortunately isn't supported by de opensearch runner.

I've tried adding it through the modules using the following code:

`public static final String OPENSEARCH_MODULES =
            "org.opensearch.analysis.common.CommonAnalysisPlugin," + //
                    "org.opensearch.transport.Netty4Plugin," + //
                    "org.opensearch.geo.GeoModulePlugin";`

...

`
runner = new OpenSearchRunner();
        runner.onBuild((number, settingsBuilder) -> {
            settingsBuilder.put("http.cors.enabled", false);
            settingsBuilder.put("discovery.type", "single-node");
            settingsBuilder.putList("discovery.seed_hosts", "127.0.0.1:9201");
            settingsBuilder.put("indices.query.bool.max_clause_count", "30000");
        }).build(OpenSearchRunner.newConfigs()
                .basePath(dataDirectory)
                .clusterName(clusterName)
                .numOfNode(1)
                .moduleTypes(OPENSEARCH_MODULES)
`

What am I doing wrong?

**Comment by Rob-Biemans** [comment]
@marevol

**Comment by marevol** [comment]
I have added the GeoModulePlugin. If version 2.18.0.1-SNAPSHOT looks good to you, I will proceed with releasing version 2.18.0.1.

**Comment by red-fenix** [comment]
Confirmed! Unit tests for Photon work perfectly now! Thanks!
